import { Graph, Geometry } from "../packages/core/src/index.js";
import BitButton from "./elements/BitButton.js";
import WordButton from "./elements/WordButton.js";
import MoveTrack from "./elements/MoveTrail.js";
import LineScale from "./elements/LineScale.js";
import QRCode from "./elements/QRCode.js";
import Roller from "./elements/RollerMonitor.js";
import NumberDisplayer from "./elements/NumMonitor.js";
import ASCIIDisplayer from "./elements/ASCIIMonitor.js";
import FlowBlock from "./elements/FlowBlock.js";
import XYCurve from "./elements/XYCurve.js";
import DataGroup from "./elements/DataGroup.js";
import RingChart from "./elements/RingChart.js";
import SlideSwitch from "./elements/SliderSwitch.js";
import TimeMonitor from "./elements/TimeMonitor.js";
import FunctionButton from "./elements/FunctionButton.js";
import MultiFuncButton from "./elements/MultiFuncButton.js";
import TrendChart from "./elements/TrendChart.js";
import OptionList from "./elements/OptionList.js";
import Gauge from "./elements/Gauge.js";
import CustomBar from "./elements/CustomBar.js";
import ImageMonitor from "./elements/ImageMonitor.js";
import GIFMonitor from "./elements/GIFMonitor.js";
// import type LvglGraph from "../../../lvgl/elements/LvglGraph.js";
import type LvglGraph from "../lvgl/elements//RubberBand.js";
import LedButton from "./elements/LedButton.js";
import ScreenButton from "./elements/ScreenButton.js";
import MultiButton from "./elements/MultiButton.js";

export function createHMIWidget(graph: LvglGraph, screen: LvObjT) {
	const dp = graph.getDefaultParent();
	let parent = dp;
	graph.batchUpdate(() => {
		let v1 = new BitButton(new Geometry(200, 200, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new QRCode(new Geometry(160, 0, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new FlowBlock(new Geometry(160, 60, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new Roller(new Geometry(270, 0, 100, 50), screen);
		graph.addCell(v1, parent);

		v1 = new TimeMonitor(new Geometry(270, 120, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new NumberDisplayer(new Geometry(390, 0, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new XYCurve(new Geometry(520, 80, 200, 200), screen);
		graph.addCell(v1, parent);
		v1 = new DataGroup(new Geometry(420, 550, 200, 200), screen);
		graph.addCell(v1, parent);
		v1 = new RingChart(new Geometry(210, 550, 200, 200), screen);
		graph.addCell(v1, parent);
		v1 = new TrendChart(new Geometry(290, 180, 200, 200), screen);
		graph.addCell(v1, parent);
		v1 = new LedButton(new Geometry(500, 280, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new ScreenButton(new Geometry(500, 340, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new MultiButton(new Geometry(500, 400, 100, 50), screen);
		graph.addCell(v1, parent);
		// v1 = new ScreenButton(new Geometry(500, 340, 100, 50), screen);
		// graph.addCell(v1, parent);
		v1 = new ASCIIDisplayer(new Geometry(500, 0, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new FunctionButton(new Geometry(380, 60, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new MultiFuncButton(new Geometry(380, 120, 100, 50), screen);
		graph.addCell(v1, parent);
		v1 = new WordButton(new Geometry(100, 100, 100, 100), screen);
		graph.addCell(v1, parent);
		v1 = new MoveTrack(new Geometry(0, 0, 100, 100), screen);
		graph.addCell(v1, parent);
		v1 = new LineScale(new Geometry(740, 20, 100, 200), screen);
		graph.addCell(v1, parent);
		v1 = new Roller(new Geometry(0, 150, 100, 100), screen);
		graph.addCell(v1, parent);
		v1 = new OptionList(new Geometry(160, 300, 100, 30), screen);
		graph.addCell(v1, parent);
		v1 = new Gauge(new Geometry(10, 300, 100, 100), screen);
		graph.addCell(v1, parent);
		v1 = new ImageMonitor(new Geometry(0, 390, 150, 150), screen);
		graph.addCell(v1, parent);
		v1 = new GIFMonitor(new Geometry(160, 390, 150, 150), screen);
		graph.addCell(v1, parent);
		v1 = new GIFMonitor(new Geometry(330, 390, 150, 150), screen);
		graph.addCell(v1, parent);
		v1 = new CustomBar(new Geometry(0, 550, 200, 200), screen);
		graph.addCell(v1, parent);
		v1 = new SlideSwitch(new Geometry(50, 780, 200, 30), screen);
		graph.addCell(v1, parent);
	});
}
