const structAndVarRelationConstants = {
	// 变量表单事件
	VARIABLE_EXCEL_OPEN: "VARIABLE_EXCEL_OPEN",
	VARIABLE_EXCEL_UPDATE: "VARIABLE_EXCEL_UPDATE",

	// 数据更新事件
	UPDATE_TREENODE_STRUCT_AND_VARRELATION_INTEGRATE:
		"UPDATE_TREENODE_STRUCT_AND_VARRELATION_INTEGRATE",

	// 结构变量关系类型
	STRUCT_VAR_RELATION_INTEGRATE: "STRUCT_VAR_RELATION_INTEGRATE",
	STRUCT_VAR_RELATION_INTEGRATE_CREATE: "STRUCT_VAR_RELATION_INTEGRATE_CREATE",

	STRUCT_VAR_RELATION_VARIABLE: "STRUCT_VAR_RELATION_VARABLE",
	STRUCT_VAR_RELATION_VARIABLE_ASSEMBLY: "STRUCT_VAR_RELATION_VARABLE_ASSEMBLY",
	STRUCT_VAR_RELATION_VARIABLE_ELEMENT: "STRUCT_VAR_RELATION_VARABLE_ELEMENT",
	STRUCT_VAR_RELATION_VARIABLE_CONNECT: "STRUCT_VAR_RELATION_VARIABLE_CONNECT",

	STRUCT_VAR_RELATION_STRUCT: "STRUCT_VAR_RELATION_STRUCT",
	STRUCT_VAR_RELATION_STRUCT_ASSEMBLY: "STRUCT_VAR_RELATION_STRUCT_ASSEMBLY",
	STRUCT_VAR_RELATION_STRUCT_ELEMENT: "STRUCT_VAR_RELATION_STRUCT_ELEMENT",

	// 事件总线
	EVENT_BUS_SA_ADD_NEW_STRUCT: "EVENT_BUS_SA_ADD_NEW_STRUCT",
	EVENT_BUS_SA_ADD_NEW_ADD: "EVENT_BUS_SA_ADD_NEW_ADD",

	// 变量管理右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_VARIABLE: "RIGHT_CLICK_STRUCT_VAR_RELATION_VARIABLE", // 变量管理 右键

	// 内部变量右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE:
		"RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE", // 内部变量 右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_GROUP:
		"RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_GROUP", // 内部变量 右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_ITEM:
		"RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_ITEM", // 内部变量元素 右键

	// 内部变量创建
	CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE:
		"CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE", // 内部变量（内部变量固定创建）
	CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_GROUP:
		"CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_GROUP", // 创建内部变量组
	CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_ITEM:
		"CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_ITEM", // 内部变量元素

	// ModbusTCPIP右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP:
		"RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP", // Modbus TCPIP 右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP_GROUP:
		"RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP_GROUP", // Modbus TCPIP组 右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP_ITEM:
		"RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP_ITEM", // Modbus TCPIP元素 右键

	// ModbusTCPIP创建
	CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP:
		"CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP", // Modbus TCPIP 创建
	CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP_GROUP:
		"CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP_GROUP", // Modbus TCPIP组 创建
	CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP_ITEM:
		"CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP_ITEM", // Modbus TCPIP元素 创建

	// 结构管理右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_STRUCT: "RIGHT_CLICK_STRUCT_VAR_RELATION_STRUCT", // 结构管理 右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_STRUCT_GROUP: "RIGHT_CLICK_STRUCT_VAR_RELATION_STRUCT_GROUP", // 结构组 右键
	RIGHT_CLICK_STRUCT_VAR_RELATION_STRUCT_ITEM: "RIGHT_CLICK_STRUCT_VAR_RELATION_STRUCT_ITEM", // 结构元素 右键

	// 结构管理创建
	CREATE_STRUCT_VAR_RELATION_STRUCT_GROUP: "CREATE_STRUCT_VAR_RELATION_STRUCT_GROUP", // 创建结构组 创建
	CREATE_STRUCT_VAR_RELATION_STRUCT_ITEM: "CREATE_STRUCT_VAR_RELATION_STRUCT_ITEM" // 创建结构元素 创建
};

export default structAndVarRelationConstants;
