const structAndVarRelationConstants = {
  // 变量表单事件
  VARIABLE_EXCEL_OPEN: "VARIABLE_EXCEL_OPEN",
  VARIABLE_EXCEL_UPDATE: "VARIABLE_EXCEL_UPDATE",

  // 数据更新事件
  UPDATE_TREENODE_STRUCT_AND_VARRELATION_INTEGRATE:
    "UPDATE_TREENODE_STRUCT_AND_VARRELATION_INTEGRATE",

  // 结构变量关系类型
  STRUCT_VAR_RELATION_INTEGRATE: "STRUCT_VAR_RELATION_INTEGRATE",
  STRUCT_VAR_RELATION_INTEGRATE_CREATE: "STRUCT_VAR_RELATION_INTEGRATE_CREATE",

  STRUCT_VAR_RELATION_VARIABLE: "STRUCT_VAR_RELATION_VARABLE",
  STRUCT_VAR_RELATION_VARIABLE_ASSEMBLY: "STRUCT_VAR_RELATION_VARABLE_ASSEMBLY",
  STRUCT_VAR_RELATION_VARIABLE_ELEMENT: "STRUCT_VAR_RELATION_VARABLE_ELEMENT",
  STRUCT_VAR_RELATION_VARIABLE_CONNECT: "STRUCT_VAR_RELATION_VARIABLE_CONNECT",

  STRUCT_VAR_RELATION_STRUCT: "STRUCT_VAR_RELATION_STRUCT",
  STRUCT_VAR_RELATION_STRUCT_ASSEMBLY: "STRUCT_VAR_RELATION_STRUCT_ASSEMBLY",
  STRUCT_VAR_RELATION_STRUCT_ELEMENT: "STRUCT_VAR_RELATION_STRUCT_ELEMENT",

  // 事件总线
  EVENT_BUS_SA_ADD_NEW_STRUCT: "EVENT_BUS_SA_ADD_NEW_STRUCT",
  EVENT_BUS_SA_ADD_NEW_ADD: "EVENT_BUS_SA_ADD_NEW_ADD",

  // 内部变量右键
  RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE:
    "RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE", // 内部变量 右键
  RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_GROUP:
    "RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_GROUP", // 内部变量 右键
  RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_ITEM:
    "RIGHT_CLICK_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_ITEM", // 内部变量元素 右键

  // 内部变量创建
  CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE:
    "CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE", // 内部变量 右键
  CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_GROUP:
    "CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_GROUP", // 内部变量 右键
  CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_ITEM:
    "CREATE_STRUCT_VAR_RELATION_INTERNAL_VARIABLE_ITEM", // 内部变量元素 右键

  // ModbusTCPIP右键
  RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP:
    "RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP",
  RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP_GROUP:
    "RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP_GROUP",
  RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP_ITEM:
    "RIGHT_CLICK_STRUCT_VAR_RELATION_MODBUS_TCPIP_ITEM",

  CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP:
    "CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP",
  CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP_GROUP:
    "CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP_GROUP",
  CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP_ITEM:
    "CREATE_STRUCT_VAR_RELATION_MODBUS_TCPIP_ITEM",
};

export default structAndVarRelationConstants;
